services:
  - type: web
    name: tailscale-vpn
    runtime: image
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TAILSCALE_AUTHKEY
        sync: false
